#-------------------------------
# General Site Settings
title: &name Carmine Paolino
logo: # You can add own logo. For example '/images/logo.png'.
description: &description I build AI tools at <a href="https://chatwithwork.com">Chat with Work</a> and <a href="https://rubyllm.com">RubyLLM</a>. Co-founded <a href="https://freshflow.ai">Freshflow</a>. Outside tech, I <a href="https://crimsonlake.live">make music</a>, run <a href="https://floppydisco.live">Floppy Disco</a>, and <a href="https://paolino.photography">take photos</a>.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://paolino.me" # the base hostname & protocol for your site, e.g. http://example.com


#-------------------------------
# Author Settings
author:
  name: *name
  image: '/images/me-04_small.jpg'
  avatar: '/images/me-04_small.jpg'
  picture: '/images/me-04_small.jpg'
  description: *description
  twitter: paolino

#-------------------------------
# Contact links

# Example of adding a new link to the footer - {icon: "ion-logo-github", link: "https://github.com"}
# Other icons can be found at https://ionicons.com/v4/
contact:
- {name: "Twitter", icon: "logo-twitter", link: "https://twitter.com/paolino"}
- {name: "GitHub",  icon: "logo-github", link: "https://github.com/crmne"}
- {name: "LinkedIn", icon: "logo-linkedin", link: "https://www.linkedin.com/in/carminepaolino"}
- {name: "Instagram", icon: "logo-instagram", link: "https://www.instagram.com/crmne/"}
- {name: "SoundCloud", icon: "logo-soundcloud", link: "https://soundcloud.com/crimsonlakemusic"}

# Footer Projects List
projects:
- {name: "Chat with Work", link: "https://chatwithwork.com"}
- {name: "RubyLLM", link: "https://rubyllm.com"}
- {name: "Floppy Disco", link: "https://floppydisco.live"}
- {name: "Mindscape Productions", link: "https://mindscape.productions"}
- {name: "Cluster Headache Tracker", link: "https://clusterheadachetracker.com"}

#-------------------------------
# Comment Section (Disqus)
disqus-identifier: # crmne # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Newsletter
mailchimp: false
sendfox: true # New setting for SendFox
mailchimp-identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
newsletter-title: Newsletter
newsletter-description: Subscribe to get my latest updates.


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Build settings
markdown: kramdown
permalink: ':title/'
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging
  - jekyll-feed

paginate: 9
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed
